language: minimal

dist: bionic

services:
  - docker

script:
  - docker build -f Dockerfile.maintainers . -t ci:latest
  - docker run -it -e TELEGRAM_TOKEN="${TELEGRAM_TOKEN}" -e WHITELIST_DEVICE="${WHITELIST_DEVICE}" -e WHITELIST_MAINTAINER="${WHITELIST_MAINTAINER}" -e GH_PERSONAL_TOKEN="${GH_PERSONAL_TOKEN}" ci
